version: 2

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/ie/pennylabs/lekkie/plugin/toolbox/Deps.kt" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

jobs:
  check:
    working_directory: ~/lekkie
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check test
      - store_artifacts:
          path: app/build/reports/

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  deploy:
    working_directory: ~/lekkie
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Generate changelog
          command: ./gradlew generateChangelog
      - run:
          name: Decrypt files
          command: bash enc/decrypt.sh
      - run:
          name: Publish APK
          command: ./gradlew publishRelease
      - run:
          name: Cleanup
          command: bash enc/encrypt.sh

workflows:
  version: 2
  check_deploy:
    jobs:
      - check:
         filters:
           branches:
             only:
               - master
               - /release-.*/
      - deploy:
         requires:
           - check
         filters:
           branches:
             only:
               - master
               - /release-.*/
