version: 2.1

config: &config
  working_directory: ~/lekkie
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 1
  environment:
    TERM: dumb

aliases:
  - &restore_gradle_cache
    key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "lib-data/build.gradle.kts" }}
  - &save_gradle_cache
    key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "lib-data/build.gradle.kts" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

jobs:
  checkout_code:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - save_cache: *save_gradle_cache

  check:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run:
          name: Check
          command: ./gradlew check test
      - store_artifacts:
          path: app/build/reports/
      - store_artifacts:
          path: lib-data/build/reports/
      - save_cache: *save_gradle_cache

  deploy:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run:
          name: Generate changelog
          command: ./gradlew generateChangelog
      - run:
          name: Decrypt files
          command: bash enc/decrypt.sh
      - run:
          name: Publish APK
          command: ./gradlew publishRelease
      - run:
          name: Cleanup
          command: bash enc/encrypt.sh

workflows:
  version: 2
  check_deploy:
    jobs:
      - checkout_code
      - check:
         requires:
           - checkout_code
         filters:
           branches:
             only:
               - master
               - /release-.*/
      - deploy:
         requires:
           - check
         filters:
           branches:
             only:
               - master
               - /release-.*/
